<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ConfiguracionController.cs" />
    <Compile Remove="Controllers\SeguridadControlller.cs" />
    <Compile Remove="PagosProcesamiento.cs" />
    <Compile Remove="PersonaOpciones.cs" />
    <Compile Remove="Servicios\IServicioHash.cs" />
    <Compile Remove="Servicios\ServicioHash.cs" />
    <Compile Remove="TarifaOpciones.cs" />
    <Compile Remove="Utilidades\FiltroAgregarCabecerasAttribute.cs" />
    <Compile Remove="Utilidades\FiltroTiempoEjecucion.cs" />
    <Compile Remove="Utilidades\MiFiltroDeAccion.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ejmplo-cors.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OutputCaching.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
